/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: (typeof import('ant-design-vue/es'))['Button']
    ACheckbox: (typeof import('ant-design-vue/es'))['Checkbox']
    ADatePicker: (typeof import('ant-design-vue/es'))['DatePicker']
    AForm: (typeof import('ant-design-vue/es'))['Form']
    AFormItem: (typeof import('ant-design-vue/es'))['FormItem']
    AImage: (typeof import('ant-design-vue/es'))['Image']
    AInput: (typeof import('ant-design-vue/es'))['Input']
    AInputNumber: (typeof import('ant-design-vue/es'))['InputNumber']
    AModal: (typeof import('ant-design-vue/es'))['Modal']
    APagination: (typeof import('ant-design-vue/es'))['Pagination']
    AppLocalePicker: (typeof import('./src/components/Application/src/AppLocalePicker.vue'))['default']
    AppLogo: (typeof import('./src/components/Application/src/AppLogo.vue'))['default']
    AppProvider: (typeof import('./src/components/Application/src/AppProvider.vue'))['default']
    ASelect: (typeof import('ant-design-vue/es'))['Select']
    ASelectOption: (typeof import('ant-design-vue/es'))['SelectOption']
    ATable: (typeof import('ant-design-vue/es'))['Table']
    AUpload: (typeof import('ant-design-vue/es'))['Upload']
    CountButton: (typeof import('./src/components/Countdown/src/CountButton.vue'))['default']
    CountdownInput: (typeof import('./src/components/Countdown/src/CountdownInput.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
