# Build stage
FROM node:21-bookworm AS build

WORKDIR /frontend

COPY package.json .
COPY . .

RUN npm install -g bun
RUN bun i
RUN bun run build

# Production stage
FROM nginx:stable-alpine

COPY --from=build /frontend/dist /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]