services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - ./db_init/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    expose:
      - 5432

  backend:
    build: ./backend/
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /backend

  frontend:
    build: ./frontend/
    expose:
      - 5173
    ports:
      - "5173:5173"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend
        - action: rebuild
          path: ./frontend/package.json