services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - ./db_init/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    expose:
      - 5432

  backend:
    build: 
      context: ./backend/
      dockerfile: dockerfile.prod
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /backend

  frontend:
    build:
      context: ./frontend/
      dockerfile: dockerfile.prod
    expose:
      - 80
    ports:
      - "5173:80"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend
        - action: rebuild
          path: ./frontend/package.json