# Build stage
FROM maven:3.9.6-amazoncorretto-21 AS build
WORKDIR /backend
COPY . .
RUN mvn clean package -DskipTests

# Run stage
FROM maven:3.9.6-amazoncorretto-21
COPY --from=build /backend/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]