spring:
    application:
        name: backend
    datasource:
        url: jdbc:postgresql://postgres:5432/app
        username: postgres
        password: pwd
        driver-class-name: org.postgresql.Driver